server:
  port: 8071
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financialdb?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    from: ${MAIL_FROM}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: financial-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: '*'
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.projectmanagement: DEBUG
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  paths-to-match: /api/**
  packages-to-scan: com.tensai.financial
  paths-to-exclude: /error
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox

stripe:
  api:
    key: ${STRIPE_API_KEY}