name: CI/CD Pipeline

on:
  push:
    branches:
      - Financial
  pull_request:
    branches:
      - Financial

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 1. Build inside the Financial folder (no -f needed)
      - name: Build with Maven
        run: mvn clean package
        working-directory: Backend/services/Financial

      # 2. Start the Spring Boot JAR in the background
      - name: Start Spring Boot Application
        run: nohup java -jar target/Financial-0.0.1-SNAPSHOT.jar &
        working-directory: Backend/services/Financial

      - name: Wait for Spring Boot to start
        run: sleep 60

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests

      # 3. Run Robot Framework tests from the Financial folder
      - name: Run Robot Framework tests
        run: robot src/RobotTest/forecastEndpoint.robot
        working-directory: Backend/services/Financial
