name: CI/CD Pipeline

on:
  push:
    branches:
      - Financial
  pull_request:
    branches:
      - Financial

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./Financial
      - name: Start Spring Boot Application
        run: nohup java -jar target/Financial-0.0.1-SNAPSHOT.jar
        # Replace "your-springboot-app.jar" with your actual jar file name.
        working-directory: ./Financial

      - name: Wait for Spring Boot to start
        run: sleep 40
        # Adjust sleep duration if your application needs more time to be fully up.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: robot src/RobotTest/forecastEndpoint.robot
        working-directory: ./Financial
        # Adjust the path if your Robot Framework tests are located elsewhere.
