name: CI/CD Pipeline

on:
  push:
    branches:
      - Financial
  pull_request:
    branches:
      - Financial

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repo history is available

      - name: Verify Repository Structure
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -f Backend/services/Financial/pom.xml

      - name: Start Spring Boot Application
        run: nohup java -jar Backend/services/Financial/target/Financial-0.0.1-SNAPSHOT.jar &

      - name: Wait for Spring Boot to start
        run: sleep 60

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: robot Backend/services/Financial/src/RobotTest/forecastEndpoint.robot
      - name: Check Financial Directory
        run: ls Backend/services/Financial